apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/name: mongo
spec:
  clusterIP: None
  selector:
    {{- include "streamingapp.selectorLabels" (dict "component" "mongo" "Release" .Release) | nindent 4 }}
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
