apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      {{- include "streamingapp.selectorLabels" (dict "component" "mongo" "Release" .Release) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "streamingapp.selectorLabels" (dict "component" "mongo" "Release" .Release) | nindent 8 }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mongo.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.mongo.storage.size }}
