apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/name: auth
spec:
  type: ClusterIP
  selector:
    {{- include "streamingapp.selectorLabels" (dict "component" "auth" "Release" .Release) | nindent 4 }}
  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
      protocol: TCP
      name: http
