apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "streamingapp.selectorLabels" (dict "component" "frontend" "Release" .Release) | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
