apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
